### PR TITLE
Images, Styling and Rudimentary Mobile Support 

### PR DESCRIPTION
**Pull request by T0RNATO**
Should be good to merge other than the URL duplication. Please advise on how to fix this - should I export it from `versions.ts`?

### CODE REVIEW

**Comment by vdvman1** [comment]
Looks pretty good, I'll allow and check out the preview build soon

And yeah, I meant exporting the URL from `versions.ts`. Specifically, there will need to be two variables, because of the `/v2/` part that isn't used in the assets but is used in the API. I can do that after I merge if you're not entirely sure what I mean

**Comment by vdvman1** [comment]
Preview looks pretty good, although there doesn't seem to be any space to the left of the version selector, which looks a little odd IMO. I did think it was odd that you removed the padding on it

**Comment by vdvman1** [comment]
Also, the selected version doesn't seem to have much styling in light mode, it only has an underline, whereas on dark mode there is a nice background as well

**Comment by vdvman1** [comment]
Looks good! I think I'm ready to merge this, if you have finished all the changes you were planning?

**Comment by T0RNATO** [comment]
Yep! Sounds good, thanks.

**Pull request merged**
